site_name: 'some-org-app'
site_description: 'Main documentation for the some-org-app project'
repo_url: https://github.com/mr-jarek/some-org-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'